# Usa uma imagem do Node.js como base
FROM node:16

# Define o diretório de trabalho
WORKDIR /app

# Copia o package.json e o package-lock.json para instalar as dependências
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos
COPY . .

# Compila o app para produção
RUN npm run build

CMD ["npm", "start"]