services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./api:/app
      - ./api/data:/app/data
      - ./api/models:/app/models 
    environment:
      - FLASK_ENV=development
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge