version: '3'

services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./api:/app
      - ./api/data:/app/data         # Mapeia a pasta 'data' para o container
      - ./api/models:/app/models 
    environment:
      - FLASK_ENV=development
    command: python app.py
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge