# Usa uma imagem do Python como base
FROM python:3.9

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos para o container
COPY . .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expõe a porta 5000 para o Flask
EXPOSE 5000

# Comando para rodar o app Flask
CMD ["python", "app.py"]
